"""Splice slides that use native chart / table parts from the original package.

pptxgenjs regenerates shapes and text faithfully, but the extractor does not
model DrawingML charts or tables. Those two slides are unchanged from the
original deck, so the original XML is copied in verbatim along with any parts
it references.
"""
import re
import shutil
import sys
import zipfile
from pathlib import Path

SRC = Path(sys.argv[1]).resolve()   # unpacked original
DST = Path(sys.argv[2]).resolve()   # unpacked generated
PAIRS = [tuple(int(v) for v in p.split(":")) for p in sys.argv[3].split(",")]
OUT = Path(sys.argv[4])
TOTAL = int(sys.argv[5])
EDITS = [tuple(e.split("=>")) for e in sys.argv[6].split("||")] if len(sys.argv) > 6 else []

ct_path = DST / "[Content_Types].xml"
content_types = ct_path.read_text(encoding="utf-8")
copied_parts = []


def ensure_override(part, ctype):
    global content_types
    if f'PartName="/{part}"' in content_types:
        return
    content_types = content_types.replace(
        "</Types>", f'<Override PartName="/{part}" ContentType="{ctype}"/></Types>')


for src_no, dst_no in PAIRS:
    src_slide = SRC / "ppt" / "slides" / f"slide{src_no}.xml"
    dst_slide = DST / "ppt" / "slides" / f"slide{dst_no}.xml"
    xml = src_slide.read_text(encoding="utf-8")
    # The original stamped "N / 26"; restamp for this deck's position and length.
    xml = re.sub(r"<a:t>\d+ / \d+</a:t>", f"<a:t>{dst_no} / {TOTAL}</a:t>", xml)
    for old, new_text in EDITS:
        xml = xml.replace(f"<a:t>{old}</a:t>", f"<a:t>{new_text}</a:t>")

    src_rels = SRC / "ppt" / "slides" / "_rels" / f"slide{src_no}.xml.rels"
    dst_rels = DST / "ppt" / "slides" / "_rels" / f"slide{dst_no}.xml.rels"
    rels = src_rels.read_text(encoding="utf-8")

    # Point the layout relationship at whatever layout the generated deck uses,
    # and drop the notes relationship (notes are regenerated by the builder).
    keep = []
    layout_target = re.search(
        r'Target="([^"]*slideLayout[^"]*)"',
        dst_rels.read_text(encoding="utf-8")).group(1)
    for rel in re.findall(r"<Relationship [^>]*/>", rels):
        if "notesSlide" in rel:
            continue
        if "slideLayout" in rel:
            rel = re.sub(r'Target="[^"]*"', f'Target="{layout_target}"', rel)
        keep.append(rel)
        target = re.search(r'Target="([^"]*)"', rel).group(1)
        if "chart" in target:
            part = target.lstrip("/")
            copied_parts.append(part)

    # Preserve the generated slide's notes relationship if it has one.
    dst_existing = dst_rels.read_text(encoding="utf-8")
    notes = re.search(r'<Relationship [^>]*notesSlide[^>]*/>', dst_existing)
    if notes:
        used = {int(m) for m in re.findall(r'Id="rId(\d+)"', "".join(keep))}
        free = max(used, default=0) + 1
        keep.append(re.sub(r'Id="rId\d+"', f'Id="rId{free}"', notes.group(0)))

    header = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
              '<Relationships xmlns="http://schemas.openxmlformats.org/package/'
              '2006/relationships">')
    dst_rels.write_text(header + "".join(keep) + "</Relationships>", encoding="utf-8")
    dst_slide.write_text(xml, encoding="utf-8")
    print(f"spliced original slide{src_no} -> slide{dst_no}")

# Copy chart parts (and anything they reference) across.
queue = list(copied_parts)
seen = set()
while queue:
    part = queue.pop()
    if part in seen:
        continue
    seen.add(part)
    src_part = SRC / part
    dst_part = DST / part
    dst_part.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_part, dst_part)
    ensure_override(part, {
        ".xml": "application/vnd.openxmlformats-officedocument.drawingml.chart+xml",
    }.get(src_part.suffix, "application/octet-stream"))

    rel_file = src_part.parent / "_rels" / (src_part.name + ".rels")
    if rel_file.exists():
        dst_rel = dst_part.parent / "_rels" / (src_part.name + ".rels")
        dst_rel.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(rel_file, dst_rel)
        base = src_part.parent
        for target in re.findall(r'Target="([^"]*)"', rel_file.read_text(encoding="utf-8")):
            resolved = ((SRC / target.lstrip("/")) if target.startswith("/")
                        else (base / target).resolve())
            queue.append(str(resolved.relative_to(SRC)))

# Embedded workbooks need a default extension entry.
if 'Extension="xlsx"' not in content_types:
    content_types = content_types.replace(
        "<Default", '<Default Extension="xlsx" ContentType="application/vnd.'
        'openxmlformats-officedocument.spreadsheetml.sheet"/><Default', 1)
ct_path.write_text(content_types, encoding="utf-8")
print("copied parts:", sorted(seen))

if OUT.exists():
    OUT.unlink()
with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
    for f in sorted(DST.rglob("*")):
        if f.is_file():
            z.write(f, f.relative_to(DST).as_posix())
print("wrote", OUT)
